### ISSUE TITLE
YAML to JSON errors running example

### ISSUE THREAD

**Issue by jascott1** [sapcc/openstack-helm#2]
Ubuntu 16.04
k8s: 1.4
helm: v2.0.0-rc.1 (also tried v2.0.0-beta.2)
openstack-helm master: 2388670907477779710a485253bd142f6acb75fd
invocation: helm install europe-example-region

After following the installation instructions and running the example, I get errors like this for several files:

Error: YAML parse error on europe-example-region/templates/nova/vmware-deployment.yaml: error converting YAML to JSON: yaml: line 30: mapping values are not allowed in this context

Still looking into it but wanted to check to see if this is a known issue. Thanks!

**Comment by abattye** [comment]
Hi,

This is the usual response from Helm/Tiller when a template operation generates invalid Yaml. It's a pretty useless error message (something we want to change in Helm) and can take some digging to find the root cause but in this case it's most likely the result of a value used in the deployment template evaluating to blank. 

One think you might want to check is that the dependencies are being brought into the chart properly. We have seen issues if the 'charts' folder is missing - it's not auto created on the dependency update, which then quietly fails. 

Andrew

**Comment by databus23** [comment]
@jascott1 Turns our our example region missed a refactoring. I committed a fix for that. Now I can at least run `helm install --dry-run --debug europe-example-region` without yaml errors.

Please by aware that this will very probaply  not give you working OpenStack installation, these charts are very tailored to our infrastructure and not generalised yet. We just published them as a reference for discussion on how OpenStack could be packaged using helm. This still needs quite a bit of work to be of practical use to anyone but us.

**Comment by jascott1** [comment]
Thanks for the effort but now I get the following errors (exact service changes each time I try install). This is a fresh checkout running your install command.

Error: parse error in "europe-example-region/charts/openstack/charts/glance/templates/_partials.tpl": template: europe-example-region/charts/openstack/charts/glance/templates/_partials.tpl:1: unexpected "\\" in define clause

**Comment by databus23** [comment]
Thats weird. Can you post the first line of the _partials.tpl file that causes this error?

**Comment by abattye** [comment]
There is an issue with our Makefile generating the _partials.tpl on Ubuntu/Linux. On OSX \" is treated as an escape sequence, not so on Ubuntu e.g. https://github.com/sapcc/openstack-helm/blob/master/glance/Makefile#L7 and so it generates something like `{{ define \"bin/glance-api-start\" }}` instead of the `{{ define "bin/glance-api-start" }}` we see on OSX

Seems it can easily be fixed/worked around (at least for Ubuntu) by removing the escaping of " in all chart Makefiles. We need to test this doesn't break our workflow.

We are also having some parallel discussions on trying to remove the chart Makefile completely. Either way we will update with a fix ASAP.

**Comment by jascott1** [comment]
Thanks! Now that the makefiles are removed it doesn't throw JSON to YAML errors when following the example install now.
